export const FETCH_WEB3_CONNECTION_REQUESTED = "App/FETCH_WEB3_CONNECTION_REQUESTED"
export const FETCH_WEB3_CONNECTION_SUCCESS = "App/FETCH_WEB3_CONNECTION_SUCCESS"
export const FETCH_WEB3_CONNECTION_FAILED = "App/FETCH_WEB3_CONNECTION_FAILED"

// 以下に自分が使うアクションを定義
export const SET_USER_ADDRESS = "App/SET_USER_ADDRESS"
export const FETCH_HISTORY_REQUESTED = "App/FETCH_HISTORY_REQUESTED"
export const FETCH_HISTORY_SUCCESS = "App/FETCH_HISTORY_SUCCSESS"
export const SEND_MESSAGE_REQUESTED = "App/SEND_MESSAGE_REQUESTED"
